version: '3.8'
services:
  app:
    build: .
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Thêm các biến môi trường khác nếu cần

    restart: always
